### ISSUE TITLE
[Bug] YouTube v19.24.2 Crashes When Loading A Video

### ISSUE THREAD

**Issue by TheNightRider12** [YTLitePlus/YTLitePlus#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iOS 10 Developer Beta 1
- Device model: iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Signulous
- The specific version of YTLitePlus: 4.0.1 (Commit: https://github.com/YTLitePlus/YTLitePlus/commit/2feb55f049c852e846eb4cfab67dcce4a89c2c5d)
- When loading a YouTube video, the app crashes upon the video loading fully. I turned off SponsorBlock, the issue still occurs. Turned off YouPIP, issue occurs still. 

### Describe the bug

When attempting to load a video, YouTube then crashes. Not sure what the issue could be. I turned off SponsorBlock and YouPIP to see if that would fix the issue, but it does not. 

### Steps to reproduce the issue

1. Install the latest YouTube app + YTLitePlus version.
2. Load up YouTube
3. Attempt to play a video
4. YouTube crashes. 

### Crash log (if the app crashes)

```shell
https://gist.github.com/TheNightRider12/16c581a33d01d4b7fd996f44216e24ba
```

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

N/A

**Comment by gleg24** [comment]
I’m having the same issue

**Comment by justinw0681** [comment]
Having the same issue here.

**Comment by justinw0681** [comment]
> Disabling Return Youtube Dislikes in settings solved this for me.

That worked, thanks!

**Comment by gleg24** [comment]
Yup that worked for me too, that’s a shame

**Comment by Balackburn** [comment]
Fixed

**Comment by hzozo** [comment]
> Fixed

Are you certain? I installed the build you created yesterday evening and it still crashed for me when loading a video. Also the bottom bar was just all wrong, icons were missing.
