### ISSUE TITLE
[Bug] (YouPiP) Can't play videos in 1440p and above

### ISSUE THREAD

**Issue by speed-y** [YTLitePlus/YTLitePlus#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 18.0 Developer Beta 2(22A5297f)
- Device model: iphone 15 pro max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): sideloadly
- The specific version of YTLitePlus (**latest** or **newest** is **NOT** a version number!): 19.24.3-4.0.1

### Describe the bug

1440p/4k Videos dont play. I get the following error:
**Something went wrong. Tap to retry.** 
Please refer to the screenshot:
![Screenshot 2024-06-29 at 14 40 47 jpeg](https://github.com/YTLitePlus/YTLitePlus/assets/25876612/86380360-aa7c-4a08-907f-dc554f74c533)

### Steps to reproduce the issue

1. Open any Video and change the quality to 1440p/2160p
2. 
3. 

### Are you using the newest version of YTLitePlus? If not, why?

✅ Yes, I'm using the latest version of YTLitePlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by JudeTheTechSavvyDude** [comment]
The same thing is happening to me as well, maybe there is a way around it who knows

**Comment by akhilyeddula** [comment]
Under Video Quality Preferences, make sure that VP9 is enabled. Then, turn off YouPIP. That should fix the issue.

**Comment by speed-y** [comment]
Yeah I can confirm this works. But this is just a workaround not a permanent solution as PiP doesn't work anymore. I would still like this issue to be open. Thanks! (:

**Comment by bhackel** [comment]
I can still get pip to work with YouPiP disabled. There’s a pip setting in General for me. I’m trying to figure out if removing YouPiP is possible since it is breaking things. If anyone has trouble getting PiP to work while YouPiP is disabled, let me know.

**Comment by speed-y** [comment]
> I can still get pip to work with YouPiP disabled. There’s a pip setting in General for me. I’m trying to figure out if removing YouPiP is possible since it is breaking things. If anyone has trouble getting PiP to work while YouPiP is disabled, let me know.

Do you mean the General settings in YouTube app? That's not available for me.

**Comment by bhackel** [comment]
Yes it’s very weird for me because it pops into existence: 

https://github.com/YTLitePlus/YTLitePlus/assets/34104885/8ceac93d-7ea2-482a-af91-33b533c100ec

**Comment by speed-y** [comment]
![image](https://github.com/YTLitePlus/YTLitePlus/assets/25876612/b6fb7c9e-f700-42bc-a1b7-87f874386e39)

Haha. It's not showing up for me

**Comment by bhackel** [comment]
Weird yea, I saw on Reddit that it may be a regional thing, maybe there is an AB flag for it, or maybe VPN will change something. I will take a look

**Comment by speed-y** [comment]
Thanks. I tried to check in AB flags. Didn't get anything that was obvious. Will try to look further. Let me know if you find something.

**Comment by bhackel** [comment]
Here’s a tweet from 2022 saying that it’s US only:
https://x.com/TeamYouTube/status/1546596110965395458

**Comment by speed-y** [comment]
> Here’s a tweet from 2022 saying that it’s US only:
> 
> https://x.com/TeamYouTube/status/1546596110965395458

Can we spoof the locale inside the app to be United states?

**Comment by ComfortableMilk4454** [comment]
@arichornloverALT will we get a fix for this soon 🙏

**Comment by bhackel** [comment]
My current idea is to make a fork of YouPiP that does not have all of the old code for older YouTube versions.

**Comment by bhackel** [comment]
Fixed in latest

**Comment by DefiniteCoding** [comment]
@bhackel to get latest, do I need to rebuild using latest fork and latest YouTube IPA version?

**Comment by bhackel** [comment]
Latest commits yes, but YouTube version can be anything above ~19.10

**Comment by sdburrows** [comment]
@bhackel I am not sure if I am building the app correctly or the bug has not been fixed. I took a fork of this repo and synced my fork and started the workflow, sideloaded the app to my phone but 1440p+ video still wont play.

**Comment by ComfortableMilk4454** [comment]
did you turn on vp9 in video quality preferences @sdburrows

**Comment by sdburrows** [comment]
@ComfortableMilk4454 It was already on, I tried turning it off but still wont play high res video. If i turn off PiP, videos play ok.

**Comment by Moolynx** [comment]
Ok after a lot of tweaking, I found that turning on "Legacy PIP" is the culprit. Is this a bug?

**Comment by bhackel** [comment]
Yea, it used to be default enabled for everyone, but an update changed that. Definitely not a recommended button to touch
